import { Inter } from "next/font/google";
import "./globals.css";
import './style.css'
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="light">
      <body className={inter.className}>

        <main className=" extracolour">
          <div className="max-w-screen-xl mx-auto">
            {children}
          </div>


        </main>

      </body>
    </html>
  );
}
